# Supabase Configuration
# Replace with your actual Supabase credentials

[supabase]
url = "https://xcziqogdqkeglwflwett.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhjemlxb2dkcWtlZ2x3Zmx3ZXR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwNjg0OTYsImV4cCI6MjA3NjY0NDQ5Nn0.zhBzEssRxerrXZME9VsalKTolbd4V6XiYUEUpSHe334"
